apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: components
spec:
  chart:
    spec:
      chart: authentik
      version: 2023.10.x # auto-update to semver bugfixes only
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: authentik
  values:
    authentik:
      secret_key: "slingingbuddyshimmer"
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
      error_reporting:
        enabled: true
      postgresql:
        password: "swiftlystronglyoverarch"

    server:
      ingress:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: lab.steppler.ai
            paths:
              - path: "/authentik"
                type: Prefix

    postgresql:
      enabled: true
      auth:
        password: "swiftlystronglyoverarch"

    redis:
      enabled: true
