apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: components
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 5.8.39
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: jenkins-value-overrides
      valuesKey: values.yaml
