apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: components
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: 5.8.39
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: flux-system
  values:
    controller:
      jenkinsUrlProtocol: "https"

      jenkinsUrl: "https://homeserver.local/jenkins"

      jenkinsUriPrefix: "/jenkins"

      usePodSecurityContext: true
      runAsUser: 1000
      fsGroup: 1000

      ingress:
        enabled: true

        apiVersion: "extensions/v1beta1"

        labels: {}
        annotations:
          kubernetes.io/ingress.class: traefik
        ingressClassName: traefik

        path: "/jenkins"
        hostName: homeserver.local

        resourceRootUrl:

        tls:
          - secretName: homeserver-tls-cert
            hosts:
              - homeserver.local
