---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: components
spec:
  interval: 24h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: ">=0.1.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: components
spec:
  targetNamespace: components
  interval: 5m
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./apps/capacitor"
  sourceRef:
    kind: OCIRepository
    name: capacitor
