apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: components
spec:
  targetNamespace: components
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./kustom/capacitor"
  sourceRef:
    kind: OCIRepository
    name: capacitor
