apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: components
  interval: 5m
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  sourceRef:
    kind: OCIRepository
    name: capacitor
    namespace: flux-system
